version: 2

project_name: orbital

before:
  hooks:
    - go mod tidy

builds:
  - id: orbital
    main: .
    binary: orbital
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/ul0gic/orbital/cmd.Version={{.Version}}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - id: orbital
    formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: checksums.txt
  algorithm: sha256

changelog:
  disable: true

release:
  draft: false
  prerelease: auto

snapshot:
  version_template: "{{ incpatch .Version }}-snapshot-{{ .ShortCommit }}"
